name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # update otomatis tiap hari
  workflow_dispatch:     # bisa dijalankan manual

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Basic info
          user: Akazelll
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Jakarta

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_colors: github

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # Achievements (aman walau masih sedikit)
          plugin_achievements: yes
          plugin_achievements_threshold: C
