name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # update tiap hari
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Base
          user: Akazelll
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_colors: github
          plugin_languages_sections: most-used

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review

          # Achievements (aman walau belum banyak)
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
